name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main  # mainブランチへのプッシュでトリガーされる

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードを取得
    - name: Checkout repository
      uses: actions/checkout@v3

    # Ruby環境のセットアップ
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3  # Gemfileで使用しているRubyバージョンを指定
        bundler-cache: true # bundlerのキャッシュを有効化

    # 依存関係をインストール
    - name: Install dependencies
      run: bundle install  # Gemfileから必要なGemをインストール

    # just-the-docsテーマをローカルにインストール
    - name: Install just-the-docs theme
      run: bundle exec gem install just-the-docs -v 0.10.0

    # Jekyllをビルド
    - name: Build the site with Jekyll
      run: bundle exec jekyll build

    # GitHub Pagesにデプロイ
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Jekyllのビルド成果物を指定