name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main  # mainブランチへのプッシュでトリガーされる

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードを取得
    - name: Checkout repository
      uses: actions/checkout@v3

    # Ruby環境のセットアップ
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2  # 使用しているRubyバージョンを指定

    # 依存関係をインストール
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install  # Gemfileから必要なGemをインストール

    # Jekyllをビルド
    - name: Build the site with Jekyll
      run: bundle exec jekyll build

    # GitHub Pagesにデプロイ
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Jekyllのビルド成果物を指定